name: randomkitselector
version: '1.0-SNAPSHOT'
main: me.literalgargoyle.randomkitselector.RandomKitSelector
api-version: '1.21'
load: STARTUP
authors: [ literal-gargoyle ]
description: An automatic kit giving plugin
website: literal-gargoyle.github.io
commands:
  RKS:
    description: Random Kit Selector commands
    usage: /RKS <create|delete|list>

permissions:
  randomkitselector.createkit:
    description: Allows the player to create a kit.
    default: op
