name: randomkitselector
version: '1.0-SNAPSHOT'
main: com.literalgagoyle.RandomKitSelector
api-version: '1.21'
load: STARTUP
authors: [ literal-gargoyle ]
description: An automatic kit giving plugin
website: literal-gargoyle.github.io

commands:
  createkit:
    description: Create a new kit based on your current inventory.
    usage: /createkit <kitName>
    permission: randomkitselector.createkit

permissions:
  randomkitselector.createkit:
    description: Allows the player to create a kit.
    default: op
